trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

jobs:
- job: Test
  timeoutInMinutes: 60
  pool:
    vmImage: ['ubuntu-latest','windows-latest']
  
  steps:
  # 1. Checkout code (Handled automatically by Azure DevOps, no step needed)

  # 2. Setup Node.js Environment
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x' # Uses LTS version of Node
    displayName: 'Install Node.js'

  # 3. Install NPM Dependencies
  - script: npm ci
    displayName: 'Install Dependencies'

  # 4. Install Playwright Browsers & OS requirements
  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  # 5. Execute your Playwright Tests
  - script: npx playwright test
    displayName: 'Run Playwright Tests'

  # 6. Upload HTML Report (Runs even if previous steps/tests fail)
  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed() 
    inputs:
      targetPath: 'playwright-report/'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    displayName: 'Upload Playwright Report'
